services:
  clickhouse-init:
    image: alpine:3.22.1

  backend:
    build: !reset null
    ports: !override []
    pull_policy: missing
    environment:
      OPIK_USAGE_REPORT_ENABLED: "false"

  python-backend:
    build: !reset null
    pull_policy: missing

  guardrails-backend:
    build: !reset null
    pull_policy: missing

  demo-data-generator:
    build: !reset null
    pull_policy: missing

  frontend:
    build: !reset null
    pull_policy: missing
    ports: !override
      - "127.0.0.1:${OPIK_HOST_PORT:-5173}:${NGINX_PORT:-5173}"

  jaeger:
    image: jaegertracing/all-in-one:1.63.0
