CREATE TABLE IF NOT EXISTS `metadata_sync_history` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `cluster_id` BIGINT NOT NULL COMMENT '数据源ID',
    `cluster_name` VARCHAR(100) DEFAULT NULL COMMENT '数据源名称',
    `source_type` VARCHAR(20) DEFAULT NULL COMMENT '数据源类型',
    `trigger_type` ENUM('manual', 'auto') NOT NULL COMMENT '触发方式',
    `scope_type` ENUM('all', 'database', 'table') NOT NULL COMMENT '同步范围类型',
    `scope_target` VARCHAR(255) DEFAULT NULL COMMENT '范围标识(库名/表名)',
    `status` ENUM('SUCCESS', 'PARTIAL', 'FAILED') NOT NULL COMMENT '同步状态',
    `started_at` DATETIME NOT NULL COMMENT '开始时间',
    `finished_at` DATETIME NOT NULL COMMENT '结束时间',
    `duration_ms` BIGINT NOT NULL DEFAULT 0 COMMENT '耗时毫秒',
    `new_tables` INT NOT NULL DEFAULT 0 COMMENT '新增表数',
    `updated_tables` INT NOT NULL DEFAULT 0 COMMENT '更新表数',
    `deleted_tables` INT NOT NULL DEFAULT 0 COMMENT '删除表数',
    `blocked_deleted_tables` INT NOT NULL DEFAULT 0 COMMENT '阻断删除表数',
    `inactivated_tables` INT NOT NULL DEFAULT 0 COMMENT '失活表数',
    `new_fields` INT NOT NULL DEFAULT 0 COMMENT '新增字段数',
    `updated_fields` INT NOT NULL DEFAULT 0 COMMENT '更新字段数',
    `deleted_fields` INT NOT NULL DEFAULT 0 COMMENT '删除字段数',
    `error_count` INT NOT NULL DEFAULT 0 COMMENT '错误数量',
    `error_summary` VARCHAR(500) DEFAULT NULL COMMENT '错误摘要',
    `error_details` MEDIUMTEXT DEFAULT NULL COMMENT '错误明细(JSON)',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    KEY `idx_sync_history_cluster_time` (`cluster_id`, `started_at`),
    KEY `idx_sync_history_status` (`status`),
    KEY `idx_sync_history_trigger` (`trigger_type`),
    KEY `idx_sync_history_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据同步历史';
