CREATE TABLE IF NOT EXISTS `schema_backup_config` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `cluster_id` BIGINT NOT NULL COMMENT '数据源ID',
    `schema_name` VARCHAR(128) NOT NULL COMMENT 'Schema名称',
    `repository_name` VARCHAR(128) NOT NULL COMMENT 'Doris仓库名',
    `minio_endpoint` VARCHAR(255) NOT NULL COMMENT 'MinIO Endpoint',
    `minio_region` VARCHAR(64) DEFAULT 'us-east-1' COMMENT 'MinIO Region',
    `minio_access_key` VARCHAR(200) NOT NULL COMMENT 'MinIO AccessKey',
    `minio_secret_key` VARCHAR(200) NOT NULL COMMENT 'MinIO SecretKey',
    `minio_bucket` VARCHAR(128) NOT NULL COMMENT 'MinIO Bucket',
    `minio_base_path` VARCHAR(255) NOT NULL COMMENT 'Bucket下备份路径',
    `use_path_style` TINYINT DEFAULT 1 COMMENT '是否启用Path Style(1-是,0-否)',
    `backup_enabled` TINYINT DEFAULT 0 COMMENT '是否开启每日定时备份(1-是,0-否)',
    `backup_time` VARCHAR(5) DEFAULT '02:00' COMMENT '每日备份时间(HH:mm)',
    `last_backup_time` DATETIME DEFAULT NULL COMMENT '最近一次触发备份时间',
    `status` VARCHAR(20) DEFAULT 'active' COMMENT '状态(active/inactive)',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_schema_backup_cluster_schema` (`cluster_id`, `schema_name`),
    KEY `idx_schema_backup_enabled` (`backup_enabled`, `backup_time`),
    KEY `idx_schema_backup_cluster` (`cluster_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Schema备份配置表';
