# GitHub Pages Configuration
theme: jekyll-theme-cayman
title: OneData Works
description: 一站式数据任务管理与数据血缘可视化平台
show_downloads: true
google_analytics: # 可以添加 Google Analytics ID

# Site settings
url: "https://mingkevan.github.io"
baseurl: "/opendataworks"

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
